@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}'
String imgTag  = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/dex:' + imgTag): 'olcne/dex:' + imgTag],
        platforms: ['ol8'],
        architectures: ['x86_64', 'aarch64'],
        publishImage: false,
        yumOL8Repos: ['ol8_codeready_builder']
)
